### ISSUE TITLE
Just Education or "Reseach and Education"?

### ISSUE THREAD

**Issue by surfnet-niels** [daserzw/oidc-edu-wg#3]
I think we represent more then "just" education ;)
So "Research and Education" seems more appropriate to use a wording in the proposal.
Whether or not that should also be reflected in the name of the working group I do not know: edu is a common abbreviation in the US for the sector as a whole I think. And if we pick e.g. R&S tha might deny us the ability to use that as a scope later on (or it might not..)

https://github.com/daserzw/oidc-edu-wg/pull/4

**Comment by daserzw** [comment]
Yes, I agree to both: R&E should be there, but we can just edu as the abbreviation of the WG. Needless to say, I welcomed your PR. Thanks!
