### ISSUE TITLE
Remove (project) specific wording in liason; add affiliations

### ISSUE THREAD

**Issue by surfnet-niels** [daserzw/oidc-edu-wg#6]
We should not use project internal references as the main nothing to the outside world (e.g. JRA-XYZ)
We should correctly attribute project to the entities they are part of like e.g. CACTI being part of I2

What are the affiliations of:
* OIDF Federations Working Group
* The eduGAIN Steering Group

**Comment by daserzw** [comment]
Yes, much of them have been already fixed by your PR. As for the eduGAIN SG, eduGAIN itself should be enough as a reference. The "OIDF Federations Working Group" is just wrong, so I got rid of it (the OIDC Federation spec is already cited as related work).
